### ISSUE TITLE
Plugin speedment:gui problems

### ISSUE THREAD

**Issue by ialoft** [speedment/speedment#160]
Hello,

I am trying to use the speedment:gui from the plugin version 2.3

1/ If information on the first screen are wrong, changes are not used for the second try.
2/ When all is good setup i got the following error

`[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building ialoft 1.0.0-BUILD-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- speedment-maven-plugin:2.3.0:gui (default-cli) @ api ---
[INFO] Running Speedment GUI
[info] Component constructors container is not defined.
2016-04-06T18:00:35.198Z INFO  [main] (c.s.i.c.r.SpeedmentApplicationLifecycle) - Speedment (Open Source) version 2.3.0 by Speedment Inc. started. API version is 2.3
[ERROR] The specified .json-file '/Users/Lamine/Google Drive/ia_work/src/main/json/speedment.json' does not exist.
Apr 06, 2016 9:00:35 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.40 by JavaFX runtime of version 8.0.25
2016-04-06T18:00:42.192Z INFO  [JavaFX Application Thread] (c.s.i.c.d.AbstractRelationalDbmsHandler) - Reading metadata from Dbms db0.db
Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: javafx/scene/control/Dialog
	at com.speedment.internal.ui.UISession.showProgressDialog(UISession.java:551)
	at com.speedment.internal.ui.UISession.loadFromDatabase(UISession.java:689)
	at com.speedment.internal.ui.controller.ConnectController.lambda$initialize$2(ConnectController.java:184)
	at com.speedment.internal.ui.controller.ConnectController$$Lambda$359/1829023931.handle(Unknown Source)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Node.fireEvent(Node.java:8216)
	at javafx.scene.control.Button.fire(Button.java:185)
	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3724)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3452)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1728)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2461)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:348)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:273)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:382)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:553)
	at com.sun.glass.ui.View.notifyMouse(View.java:925)
Caused by: java.lang.ClassNotFoundException: javafx.scene.control.Dialog
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:244)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:230)
	... 46 more
2016-04-06T18:00:42.293Z INFO  [ForkJoinPool.commonPool-worker-0] (c.s.i.c.d.AbstractRelationalDbmsHandler) - Reading metadata from Schema db.db0`

PS : I use speedment v2.3 + JDBC MariaDB

Thank you

**Comment by ialoft** [comment]
SOLVED

The new plugin require java 1.8.0_77 (the more recent one), i was previously running under 1.8.0_25

PS : new gui is much better thank you guy :-)

**Comment by minborg** [comment]
Thanks for the input! I think you are running an old version of Java 8. Make sure you use the latest and greatest JDK 8 (77 right now). It appears as you are running 8.0.25. Oracle changed the API a bit in 40

**Comment by minborg** [comment]
OK. Great. I'll mark this issue as resolved.

**Comment by minborg** [comment]
Added check for version in welcome messages
``` if (package_.getImplementationVersion().compareToIgnoreCase("1.8.0_40") < 0) {
                LOGGER.warn("The Java version is too low. Please upgrate to a more recent Java version.");
            } ```
