### ISSUE TITLE
Compability issue with later versions of MySQL connector

### ISSUE THREAD

**Issue by Pyknic** [speedment/speedment#190]
There appears to be compability issues that prevent you from using Speedment togather with newer version of the MySQL driver. If you try to upgrade to `6.x.x`, you get a `NullPointerException`.

The bug occurs when Speedment attempts to connect to the database using the connection string seen in the trace bellow. 

Version used:
- MySQL Driver `6.0.2` 
- MySQL `5.6.29`
- Speedment `2.3.1`

```
java.util.concurrent.CompletionException: com.speedment.exception.SpeedmentException: Unable to get connection for DbmsImpl {"expanded": true, "port": 3306.0, "schemas": [0], "name": database, "typeName": MySQL, "ipAddress": 127.0.0.1, "connectionUrl": jdbc:mysql://127.0.0.1:3306/?useUnicode=true&characterEncoding=UTF-8&useServerPrepStmts=true&useCursorFetch=true&zeroDateTimeBehavior=convertToNull&useSSL=false, "enabled": true, "username": accounting} using url "jdbc:mysql://127.0.0.1:3306/?useUnicode=true&characterEncoding=UTF-8&useServerPrepStmts=true&useCursorFetch=true&zeroDateTimeBehavior=convertToNull&useSSL=false", user = accounting, password = ********
    at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
    at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
    at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1629)
    at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.speedment.exception.SpeedmentException: Unable to get connection for DbmsImpl {"expanded": true, "port": 3306.0, "schemas": [0], "name": database, "typeName": MySQL, "ipAddress": 127.0.0.1, "connectionUrl": jdbc:mysql://127.0.0.1:3306/?useUnicode=true&characterEncoding=UTF-8&useServerPrepStmts=true&useCursorFetch=true&zeroDateTimeBehavior=convertToNull&useSSL=false, "enabled": true, "username": accounting} using url "jdbc:mysql://127.0.0.1:3306/?useUnicode=true&characterEncoding=UTF-8&useServerPrepStmts=true&useCursorFetch=true&zeroDateTimeBehavior=convertToNull&useSSL=false", user = accounting, password = ********
    at com.speedment.internal.core.db.AbstractRelationalDbmsHandler.getConnection(AbstractRelationalDbmsHandler.java:921)
    at com.speedment.internal.core.db.AbstractRelationalDbmsHandler.lambda$readSchemaMetadata$4(AbstractRelationalDbmsHandler.java:179)
    at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
    ... 5 more
Caused by: java.sql.SQLNonTransientConnectionException: Could not create connection to database server.
    at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:676)
    at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:663)
    at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:653)
    at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:638)
    at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:606)
    at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:1857)
    at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:1673)
    at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:656)
    at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:349)
    at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:221)
    at java.sql.DriverManager.getConnection(DriverManager.java:664)
    at java.sql.DriverManager.getConnection(DriverManager.java:247)
    at com.speedment.internal.core.platform.component.impl.ConnectionPoolComponentImpl.newConnection(ConnectionPoolComponentImpl.java:111)
    at com.speedment.internal.core.platform.component.impl.ConnectionPoolComponentImpl.getConnection(ConnectionPoolComponentImpl.java:81)
    at com.speedment.internal.core.db.AbstractRelationalDbmsHandler.getConnection(AbstractRelationalDbmsHandler.java:913)
    ... 7 more
Caused by: java.lang.NullPointerException
    at java.util.Properties$LineReader.readLine(Properties.java:434)
    at java.util.Properties.load0(Properties.java:353)
    at java.util.Properties.load(Properties.java:341)
    at com.mysql.cj.jdbc.util.TimeUtil.loadTimeZoneMappings(TimeUtil.java:163)
    at com.mysql.cj.jdbc.util.TimeUtil.getCanonicalTimezone(TimeUtil.java:109)
    at com.mysql.cj.mysqla.MysqlaSession.configureTimezone(MysqlaSession.java:308)
    at com.mysql.cj.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:2474)
    at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:1817)
    ... 16 more
```

**Comment by minborg** [comment]
The new driver loads a new class ```com.mysql.cj.jdbc.Driver``` instead of the old ```com.mysql.cj.jdbc.Driver``` . We could create a new Driver for this generation of JDBC driver or make the old one handle several driver classes.

**Comment by Rajvinder** [comment]
Hi Per-Ake,

Does this issue also occurs with Oracle and postgresql?

Thanks,
Rajvinder Kaur

**Comment by Pyknic** [comment]
I havn't tried on other databases, I just assumed it was related to MySQL since it works with version `5.1.37` but not with `6.0.2`.

**Comment by Rajvinder** [comment]
Using MYSQL 6.0.2, following exception trace found, it seems different from the above..

2016-07-06T19:51:40.302Z ERROR [JavaFX Application Thread] (c.s.i.u.UISession) - A problem occured with establishing the database connection.
java.util.concurrent.CompletionException: com.speedment.exception.SpeedmentException: java.sql.SQLException: Table name pattern can not be NULL or empty.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:961)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1632)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.speedment.exception.SpeedmentException: java.sql.SQLException: Table name pattern can not be NULL or empty.
	at com.speedment.internal.core.db.AbstractRelationalDbmsHandler.tables(AbstractRelationalDbmsHandler.java:316)
	at com.speedment.internal.core.db.AbstractRelationalDbmsHandler.lambda$null$637(AbstractRelationalDbmsHandler.java:247)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438)
	at com.speedment.internal.core.db.AbstractRelationalDbmsHandler.lambda$readSchemaMetadata$640(AbstractRelationalDbmsHandler.java:248)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	... 8 more
Caused by: java.sql.SQLException: Table name pattern can not be NULL or empty.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:695)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:663)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:653)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:638)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:606)
	at com.mysql.cj.jdbc.DatabaseMetaData.getTables(DatabaseMetaData.java:3834)
	at com.speedment.internal.core.db.AbstractRelationalDbmsHandler.tables(AbstractRelationalDbmsHandler.java:292)
	... 19 more

**Comment by minborg** [comment]
Here is a tip: https://liquibase.jira.com/browse/CORE-2723

**Comment by lawesson** [comment]
Initial investigation:

The original problem (NPE caused by bug in time zone mapping) reported by Emil seems to be related to MySQL Bug #79343 https://bugs.mysql.com/bug.php?id=79343 . Explicitly setting serverTimezone in the connection URL makes the problem go away.

The referenced issue (Table name pattern can not be NULL) can be solved by adding nullNamePatternMatchesAll=true to the connection URL.

**Comment by minborg** [comment]
Tuned out we needed to disable useCursorFetch=true
