### ISSUE TITLE
column "PUBLIC" of relation "ADINFO" does not exist

### ISSUE THREAD

**Issue by shi00** [speedment/speedment#219]
I am a newbie, my project use speedment with postgresql.
Exception：
2016-06-13T07:24:29.844Z INFO  [main] (c.s.i.c.r.SpeedmentApplicationLifecycle) - GaussDB, 9.2.1, PostgreSQL Native Driver PostgreSQL 9.1 JDBC4 (build 902), JDBC version 4.0
2016-06-13T07:24:30.031Z INFO  [main] (c.s.i.c.r.SpeedmentApplicationLifecycle) - Java Platform API Specification 1.8 by Oracle Corporation. Implementation Oracle Corporation 1.8.0_91 by Oracle Corporation
2016-06-13T07:24:30.031Z INFO  [main] (c.s.i.c.r.SpeedmentApplicationLifecycle) - Speedment (Open Source) version 2.3.4 by Speedment Inc. started. API version is 2.3
2016-06-13T07:24:30.125Z ERROR [main] (c.s.i.c.d.AbstractRelationalDbmsHandler) - SqlStatementList: [INSERT INTO "PUBLIC"."ADINFO" ("PUBLIC"."ADINFO"."ID","PUBLIC"."ADINFO"."ADTYPE","PUBLIC"."ADINFO"."DOMAIN","PUBLIC"."ADINFO"."DOMAINPASSWORD","PUBLIC"."ADINFO"."DOMAINUSER","PUBLIC"."ADINFO"."MASTERADIP","PUBLIC"."ADINFO"."MASTERDNSIP","PUBLIC"."ADINFO"."SLAVEADIP","PUBLIC"."ADINFO"."SLAVEDNSIP","PUBLIC"."ADINFO"."STATUS","PUBLIC"."ADINFO"."TENANTINFO_ID") VALUES (?,?,?,?,?,?,?,?,?,?,?), [1, samba, mytest.com, Huawei123, administrator, 192.154.190.7, 192.154.190.7, 192.154.190.8, 192.154.190.8, ok, tenant1]]
2016-06-13T07:24:30.125Z ERROR [main] (c.s.i.c.d.AbstractRelationalDbmsHandler) - SQL: INSERT INTO "PUBLIC"."ADINFO" ("PUBLIC"."ADINFO"."ID","PUBLIC"."ADINFO"."ADTYPE","PUBLIC"."ADINFO"."DOMAIN","PUBLIC"."ADINFO"."DOMAINPASSWORD","PUBLIC"."ADINFO"."DOMAINUSER","PUBLIC"."ADINFO"."MASTERADIP","PUBLIC"."ADINFO"."MASTERDNSIP","PUBLIC"."ADINFO"."SLAVEADIP","PUBLIC"."ADINFO"."SLAVEDNSIP","PUBLIC"."ADINFO"."STATUS","PUBLIC"."ADINFO"."TENANTINFO_ID") VALUES (?,?,?,?,?,?,?,?,?,?,?), [1, samba, mytest.com, Huawei123, administrator, 192.154.190.7, 192.154.190.7, 192.154.190.8, 192.154.190.8, ok, tenant1]
2016-06-13T07:24:30.125Z ERROR [main] (c.s.i.c.d.AbstractRelationalDbmsHandler) - ERROR: column "PUBLIC" of relation "ADINFO" does not exist
  位置：32
org.postgresql.util.PSQLException: ERROR: column "PUBLIC" of relation "ADINFO" does not exist
  位置：32
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2199)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:348)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:545)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:365)
	at com.speedment.internal.core.db.AbstractRelationalDbmsHandler.handleSqlStatement(AbstractRelationalDbmsHandler.java:798)
	at com.speedment.internal.core.db.AbstractRelationalDbmsHandler.execute(AbstractRelationalDbmsHandler.java:728)
	at com.speedment.internal.core.db.AbstractRelationalDbmsHandler.executeInsert(AbstractRelationalDbmsHandler.java:697)
	at com.speedment.internal.core.manager.sql.AbstractSqlManager.lambda$executeInsert$25(AbstractSqlManager.java:456)
	at com.speedment.internal.core.manager.sql.AbstractSqlManager.executeHelper(AbstractSqlManager.java:493)
	at com.speedment.internal.core.manager.sql.AbstractSqlManager.executeInsert(AbstractSqlManager.java:455)
	at com.speedment.internal.core.manager.sql.AbstractSqlManager.persistHelp(AbstractSqlManager.java:348)
	at com.speedment.internal.core.manager.sql.AbstractSqlManager.persist(AbstractSqlManager.java:174)
	at com.speedment.internal.core.code.AbstractBaseEntity.persist(AbstractBaseEntity.java:56)
	at com.silong.Main.main(Main.java:20)

Exception in thread "main" com.speedment.exception.SpeedmentException: org.postgresql.util.PSQLException: ERROR: column "PUBLIC" of relation "ADINFO" does not exist
  位置：32
	at com.speedment.internal.core.manager.sql.AbstractSqlManager.executeHelper(AbstractSqlManager.java:498)
	at com.speedment.internal.core.manager.sql.AbstractSqlManager.executeInsert(AbstractSqlManager.java:455)
	at com.speedment.internal.core.manager.sql.AbstractSqlManager.persistHelp(AbstractSqlManager.java:348)
	at com.speedment.internal.core.manager.sql.AbstractSqlManager.persist(AbstractSqlManager.java:174)
	at com.speedment.internal.core.code.AbstractBaseEntity.persist(AbstractBaseEntity.java:56)
	at com.silong.Main.main(Main.java:20)
Caused by: org.postgresql.util.PSQLException: ERROR: column "PUBLIC" of relation "ADINFO" does not exist
  位置：32
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2199)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:348)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:545)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:365)
	at com.speedment.internal.core.db.AbstractRelationalDbmsHandler.handleSqlStatement(AbstractRelationalDbmsHandler.java:798)
	at com.speedment.internal.core.db.AbstractRelationalDbmsHandler.execute(AbstractRelationalDbmsHandler.java:728)
	at com.speedment.internal.core.db.AbstractRelationalDbmsHandler.executeInsert(AbstractRelationalDbmsHandler.java:697)
	at com.speedment.internal.core.manager.sql.AbstractSqlManager.lambda$executeInsert$25(AbstractSqlManager.java:456)
	at com.speedment.internal.core.manager.sql.AbstractSqlManager.executeHelper(AbstractSqlManager.java:493)
	... 5 more
2016-06-13T07:24:51.046Z ERROR [Thread-0] (c.s.i.u.a.LoggingAdapterImpl) - Connection timed out: connect

CreateTable.sql：
DROP TABLE IF EXISTS ADINFO;
CREATE TABLE ADINFO (
    ID CHARACTER VARYING(255) NOT NULL,
    ADTYPE CHARACTER VARYING(255),
    DOMAIN CHARACTER VARYING(255),
    DOMAINPASSWORD CHARACTER VARYING(5000),
    DOMAINUSER CHARACTER VARYING(255),
    MASTERADIP CHARACTER VARYING(255),
    MASTERDNSIP CHARACTER VARYING(255),
    SLAVEADIP CHARACTER VARYING(255),
    SLAVEDNSIP CHARACTER VARYING(255),
    STATUS CHARACTER VARYING(255),
    TENANTINFO_ID CHARACTER VARYING(255),
	PRIMARY KEY (ID)
);

**Comment by minborg** [comment]
I have been able to reproduce the error.

**Comment by minborg** [comment]
We are releasing a new version due to this bug.

**Comment by minborg** [comment]
@shi00 Check out the new version 2.3.5 where this issue has been fixed. It will be available on Maven shortly.

**Comment by shi00** [comment]
Thank you，I will try later. : )
