### ISSUE TITLE
org.postgresql.util.PSQLException: Bad value for type long : ae048096-56de-4b69-976a-35ec8d89fe7e

### ISSUE THREAD

**Issue by shi00** [speedment/speedment#221]
I create  my table with primarykey id that is character varying in postgresql. 
DROP TABLE IF EXISTS ADINFO;
CREATE TABLE ADINFO (
    ID CHARACTER VARYING(255) NOT NULL,
    ADTYPE CHARACTER VARYING(255),
    DOMAIN CHARACTER VARYING(255),
    DOMAINPASSWORD CHARACTER VARYING(5000),
    DOMAINUSER CHARACTER VARYING(255),
    MASTERADIP CHARACTER VARYING(255),
    MASTERDNSIP CHARACTER VARYING(255),
    SLAVEADIP CHARACTER VARYING(255),
    SLAVEDNSIP CHARACTER VARYING(255),
    STATUS CHARACTER VARYING(255),
    TENANTINFO_ID CHARACTER VARYING(255),
    PRIMARY KEY (ID)
);

When i insert a record into the table, speedment produce the exception as follows:
2016-06-13T08:25:43.558Z INFO  [main](c.s.i.c.r.SpeedmentApplicationLifecycle) - PostgreSQL, 9.5.3, PostgreSQL Native Driver PostgreSQL 9.4 JDBC4 (build 1206), JDBC version 4.0
2016-06-13T08:25:43.605Z INFO  [main](c.s.i.c.r.SpeedmentApplicationLifecycle) - Java Platform API Specification 1.8 by Oracle Corporation. Implementation Oracle Corporation 1.8.0_91 by Oracle Corporation
2016-06-13T08:25:43.605Z INFO  [main](c.s.i.c.r.SpeedmentApplicationLifecycle) - Speedment (Open Source) version 2.3.4 by Speedment Inc. started. API version is 2.3
2016-06-13T08:25:43.793Z ERROR [main](c.s.i.c.d.AbstractRelationalDbmsHandler) - SqlStatementList: [INSERT INTO "public"."adinfo" ("id","adtype","domain","domainpassword","domainuser","masteradip","masterdnsip","slaveadip","slavednsip","status","tenantinfo_id") VALUES (?,?,?,?,?,?,?,?,?,?,?), [ae048096-56de-4b69-976a-35ec8d89fe7e, null, null, null, null, null, null, null, null, null, null]]
2016-06-13T08:25:43.793Z ERROR [main](c.s.i.c.d.AbstractRelationalDbmsHandler) - SQL: INSERT INTO "public"."adinfo" ("id","adtype","domain","domainpassword","domainuser","masteradip","masterdnsip","slaveadip","slavednsip","status","tenantinfo_id") VALUES (?,?,?,?,?,?,?,?,?,?,?), [ae048096-56de-4b69-976a-35ec8d89fe7e, null, null, null, null, null, null, null, null, null, null]
2016-06-13T08:25:43.793Z ERROR [main](c.s.i.c.d.AbstractRelationalDbmsHandler) - Bad value for type long : ae048096-56de-4b69-976a-35ec8d89fe7e
org.postgresql.util.PSQLException: Bad value for type long: ae048096-56de-4b69-976a-35ec8d89fe7e
    at org.postgresql.jdbc2.AbstractJdbc2ResultSet.toLong(AbstractJdbc2ResultSet.java:3087)
    at org.postgresql.jdbc2.AbstractJdbc2ResultSet.getLong(AbstractJdbc2ResultSet.java:2212)
    at com.speedment.internal.core.db.AbstractRelationalDbmsHandler.handleSqlStatement(AbstractRelationalDbmsHandler.java:802)
    at com.speedment.internal.core.db.AbstractRelationalDbmsHandler.execute(AbstractRelationalDbmsHandler.java:728)
    at com.speedment.internal.core.db.AbstractRelationalDbmsHandler.executeInsert(AbstractRelationalDbmsHandler.java:697)
    at com.speedment.internal.core.manager.sql.AbstractSqlManager.lambda$executeInsert$587(AbstractSqlManager.java:456)
    at com.speedment.internal.core.manager.sql.AbstractSqlManager.executeHelper(AbstractSqlManager.java:493)
    at com.speedment.internal.core.manager.sql.AbstractSqlManager.executeInsert(AbstractSqlManager.java:455)
    at com.speedment.internal.core.manager.sql.AbstractSqlManager.persistHelp(AbstractSqlManager.java:348)
    at com.speedment.internal.core.manager.sql.AbstractSqlManager.persist(AbstractSqlManager.java:174)
    at com.speedment.internal.core.code.AbstractBaseEntity.persist(AbstractBaseEntity.java:56)
    at com.silong.Main.main(Main.java:19)

Exception in thread "main" com.speedment.exception.SpeedmentException: org.postgresql.util.PSQLException: Bad value for type long: ae048096-56de-4b69-976a-35ec8d89fe7e
    at com.speedment.internal.core.manager.sql.AbstractSqlManager.executeHelper(AbstractSqlManager.java:498)
    at com.speedment.internal.core.manager.sql.AbstractSqlManager.executeInsert(AbstractSqlManager.java:455)
    at com.speedment.internal.core.manager.sql.AbstractSqlManager.persistHelp(AbstractSqlManager.java:348)
    at com.speedment.internal.core.manager.sql.AbstractSqlManager.persist(AbstractSqlManager.java:174)
    at com.speedment.internal.core.code.AbstractBaseEntity.persist(AbstractBaseEntity.java:56)
    at com.silong.Main.main(Main.java:19)
Caused by: org.postgresql.util.PSQLException: Bad value for type long : ae048096-56de-4b69-976a-35ec8d89fe7e
    at org.postgresql.jdbc2.AbstractJdbc2ResultSet.toLong(AbstractJdbc2ResultSet.java:3087)
    at org.postgresql.jdbc2.AbstractJdbc2ResultSet.getLong(AbstractJdbc2ResultSet.java:2212)
    at com.speedment.internal.core.db.AbstractRelationalDbmsHandler.handleSqlStatement(AbstractRelationalDbmsHandler.java:802)
    at com.speedment.internal.core.db.AbstractRelationalDbmsHandler.execute(AbstractRelationalDbmsHandler.java:728)
    at com.speedment.internal.core.db.AbstractRelationalDbmsHandler.executeInsert(AbstractRelationalDbmsHandler.java:697)
    at com.speedment.internal.core.manager.sql.AbstractSqlManager.lambda$executeInsert$587(AbstractSqlManager.java:456)
    at com.speedment.internal.core.manager.sql.AbstractSqlManager.executeHelper(AbstractSqlManager.java:493)
    ... 5 more

**Comment by minborg** [comment]
If you execute the SQL code manually agains the table with:
<pre>
INSERT INTO "public"."adinfo" ("id","adtype","domain","domainpassword","domainuser","masteradip","masterdnsip","slaveadip","slavednsip","status","tenantinfo_id") VALUES ('ae048096-56de-4b69-976a-35ec8d89fe7e', null, null, null, null, null, null, null, null, null, null) 
</pre>
What is the result of that?

**Comment by shi00** [comment]
I modify the sql and  run it on pgadmin console，it' s ok.
INSERT INTO adinfo 
(id,adtype,domain,domainpassword,domainuser,masteradip,masterdnsip,slaveadip,slavednsip,status,tenantinfo_id) 
VALUES 
('ae048096-56de-4b69-976a-35ec8d89fe7e', null, null, null, null, null, null, null, null, null, null);

==============================================================================
I think AbstractRelationalDbmsHandler.handleSqlStatement is missing the case of the primarykey is  string，it process the primary key is int only.
I was inexperienced, I understand may be wrong。 : )
