### ISSUE TITLE
LongForeignKeyFieldImpl does not have trait.HasFinder - needed by JsonEncoderImpl.put with finder

### ISSUE THREAD

**Issue by lawesson** [speedment/speedment#260]
The following code in the socialnetwork tutorial Server causes an exception at JsonEncoderImpl.java:278 since the field (a LongForeignKeyFieldImpl) does not have a finder.

in Server:

```java        
         jsonImageEncoder = JsonEncoder
                .allOf(images)
                .put(Image.UPLOADER,
                        JsonEncoder.allOf(users)
                                .remove(User.AVATAR)
                                .remove(User.PASSWORD)
                );
```

Exception thrown by the put() method:

Exception in thread "main" java.lang.BootstrapMethodError: call site initialization exception
	at java.lang.invoke.CallSite.makeSite(CallSite.java:341)
	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
	at com.speedment.plugins.json.internal.JsonEncoderImpl.put(JsonEncoderImpl.java:278)
	at com.speedment.examples.socialserver.Server.<init>(Server.java:54)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at fi.iki.elonen.ServerRunner.run(ServerRunner.java:41)
	at com.speedment.examples.socialserver.Server.main(Server.java:249)
Caused by: java.lang.invoke.LambdaConversionException: Invalid receiver type interface com.speedment.runtime.field.Field; not a subtype of implementation type interface com.speedment.runtime.field.trait.HasFinder
	at java.lang.invoke.AbstractValidatingLambdaMetafactory.validateMetafactoryArgs(AbstractValidatingLambdaMetafactory.java:233)
	at java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:303)
	at java.lang.invoke.CallSite.makeSite(CallSite.java:302)
	... 11 more

speedment.json attached for reference:
```json
{
  "config" : {
    "expanded" : true,
    "companyName" : "company",
    "name" : "socialnetwork",
    "packageLocation" : "src/main/java/",
    "dbmses" : [
      {
        "expanded" : true,
        "port" : 3306,
        "schemas" : [
          {
            "tables" : [
              {
                "foreignKeys" : [
                  {
                    "expanded" : false,
                    "foreignKeyColumns" : [
                      {
                        "foreignDatabaseName" : "db0",
                        "foreignSchemaName" : "socialnetwork",
                        "expanded" : true,
                        "name" : "uploader",
                        "foreignColumnName" : "id",
                        "foreignTableName" : "user",
                        "ordinalPosition" : 1
                      }
                    ],
                    "name" : "image_uploader_to_user_id"
                  }
                ],
                "expanded" : true,
                "primaryKeyColumns" : [
                  {
                    "expanded" : true,
                    "name" : "id",
                    "ordinalPosition" : 1
                  }
                ],
                "indexes" : [
                  {
                    "expanded" : false,
                    "unique" : true,
                    "name" : "PRIMARY",
                    "indexColumns" : [
                      {
                        "orderType" : "ASC",
                        "expanded" : true,
                        "name" : "id",
                        "ordinalPosition" : 1
                      }
                    ]
                  },
                  {
                    "expanded" : false,
                    "unique" : false,
                    "name" : "image_uploader_to_user_id",
                    "indexColumns" : [
                      {
                        "orderType" : "ASC",
                        "expanded" : true,
                        "name" : "uploader",
                        "ordinalPosition" : 1
                      }
                    ]
                  }
                ],
                "columns" : [
                  {
                    "databaseType" : "java.lang.Long",
                    "typeMapper" : "com.speedment.runtime.config.mapper.primitive.PrimitiveTypeMapper",
                    "expanded" : true,
                    "nullable" : false,
                    "autoIncrement" : true,
                    "name" : "id",
                    "ordinalPosition" : 1
                  },
                  {
                    "databaseType" : "java.lang.Long",
                    "typeMapper" : "com.speedment.runtime.config.mapper.primitive.PrimitiveTypeMapper",
                    "expanded" : true,
                    "nullable" : false,
                    "name" : "uploader",
                    "ordinalPosition" : 2
                  },
                  {
                    "databaseType" : "java.lang.String",
                    "expanded" : true,
                    "nullable" : false,
                    "name" : "title",
                    "ordinalPosition" : 3
                  },
                  {
                    "databaseType" : "java.lang.String",
                    "expanded" : true,
                    "nullable" : false,
                    "name" : "description",
                    "ordinalPosition" : 4
                  },
                  {
                    "databaseType" : "java.lang.String",
                    "expanded" : true,
                    "nullable" : false,
                    "name" : "img_data",
                    "ordinalPosition" : 5
                  },
                  {
                    "databaseType" : "java.sql.Timestamp",
                    "expanded" : true,
                    "nullable" : false,
                    "name" : "uploaded",
                    "ordinalPosition" : 6
                  }
                ],
                "name" : "image"
              },
              {
                "foreignKeys" : [
                  {
                    "expanded" : false,
                    "foreignKeyColumns" : [
                      {
                        "foreignDatabaseName" : "db0",
                        "foreignSchemaName" : "socialnetwork",
                        "expanded" : true,
                        "name" : "follower",
                        "foreignColumnName" : "id",
                        "foreignTableName" : "user",
                        "ordinalPosition" : 1
                      }
                    ],
                    "name" : "follow_follower_to_user_id"
                  },
                  {
                    "expanded" : false,
                    "foreignKeyColumns" : [
                      {
                        "foreignDatabaseName" : "db0",
                        "foreignSchemaName" : "socialnetwork",
                        "expanded" : true,
                        "name" : "follows",
                        "foreignColumnName" : "id",
                        "foreignTableName" : "user",
                        "ordinalPosition" : 1
                      }
                    ],
                    "name" : "follow_follows_to_user_id"
                  }
                ],
                "expanded" : true,
                "primaryKeyColumns" : [
                  {
                    "expanded" : true,
                    "name" : "follower",
                    "ordinalPosition" : 1
                  },
                  {
                    "expanded" : true,
                    "name" : "follows",
                    "ordinalPosition" : 2
                  }
                ],
                "indexes" : [
                  {
                    "expanded" : false,
                    "unique" : true,
                    "name" : "PRIMARY",
                    "indexColumns" : [
                      {
                        "orderType" : "ASC",
                        "expanded" : true,
                        "name" : "follower",
                        "ordinalPosition" : 1
                      },
                      {
                        "orderType" : "ASC",
                        "expanded" : true,
                        "name" : "follows",
                        "ordinalPosition" : 2
                      }
                    ]
                  },
                  {
                    "expanded" : false,
                    "unique" : false,
                    "name" : "follow_follows_to_user_id",
                    "indexColumns" : [
                      {
                        "orderType" : "ASC",
                        "expanded" : true,
                        "name" : "follows",
                        "ordinalPosition" : 1
                      }
                    ]
                  }
                ],
                "columns" : [
                  {
                    "databaseType" : "java.lang.Long",
                    "typeMapper" : "com.speedment.runtime.config.mapper.primitive.PrimitiveTypeMapper",
                    "expanded" : true,
                    "nullable" : false,
                    "name" : "follower",
                    "ordinalPosition" : 1
                  },
                  {
                    "databaseType" : "java.lang.Long",
                    "typeMapper" : "com.speedment.runtime.config.mapper.primitive.PrimitiveTypeMapper",
                    "expanded" : true,
                    "nullable" : false,
                    "name" : "follows",
                    "ordinalPosition" : 2
                  }
                ],
                "name" : "link"
              },
              {
                "expanded" : true,
                "primaryKeyColumns" : [
                  {
                    "expanded" : true,
                    "name" : "id",
                    "ordinalPosition" : 1
                  }
                ],
                "indexes" : [
                  {
                    "expanded" : false,
                    "unique" : true,
                    "name" : "PRIMARY",
                    "indexColumns" : [
                      {
                        "orderType" : "ASC",
                        "expanded" : true,
                        "name" : "id",
                        "ordinalPosition" : 1
                      }
                    ]
                  }
                ],
                "columns" : [
                  {
                    "databaseType" : "java.lang.Long",
                    "typeMapper" : "com.speedment.runtime.config.mapper.primitive.PrimitiveTypeMapper",
                    "expanded" : true,
                    "nullable" : false,
                    "autoIncrement" : true,
                    "name" : "id",
                    "ordinalPosition" : 1
                  },
                  {
                    "databaseType" : "java.lang.String",
                    "expanded" : true,
                    "nullable" : false,
                    "name" : "mail",
                    "ordinalPosition" : 2
                  },
                  {
                    "databaseType" : "java.lang.String",
                    "expanded" : true,
                    "nullable" : false,
                    "name" : "password",
                    "ordinalPosition" : 3
                  },
                  {
                    "databaseType" : "java.lang.String",
                    "expanded" : true,
                    "nullable" : true,
                    "name" : "first_name",
                    "ordinalPosition" : 4
                  },
                  {
                    "databaseType" : "java.lang.String",
                    "expanded" : true,
                    "nullable" : true,
                    "name" : "last_name",
                    "ordinalPosition" : 5
                  },
                  {
                    "databaseType" : "java.lang.String",
                    "expanded" : true,
                    "nullable" : true,
                    "name" : "avatar",
                    "ordinalPosition" : 6
                  }
                ],
                "name" : "user"
              }
            ],
            "expanded" : true,
            "name" : "socialnetwork"
          }
        ],
        "typeName" : "MySQL",
        "ipAddress" : "127.0.0.1",
        "name" : "db0",
        "username" : "root"
      }
    ],
    "enabled" : true
  }
}
```

**Comment by lawesson** [comment]
The compiler does not recognize that the method reference `field::findFrom` is ambiguous. At compile time it refers to 

```default FK_ENTITY findFrom(ENTITY entity, Manager<FK_ENTITY> foreignManager) ```

in the `HasFinder` trait interface, while at runtime it happens to resolve to

```FindFrom<ENTITY, FK_ENTITY> findFrom(Manager<FK_ENTITY> var1);```

in the same interface yielding a bootstrap exception at runtime. The fix is to reference the proper method with a lamdba.
