### ISSUE TITLE
Error when outputting to log

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#299]
A connection that resulted in a connection error was made. Then:
<pre>
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Called endChange before beginChange
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1629)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.IllegalStateException: Called endChange before beginChange
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:538)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.collections.ModifiableObservableListBase.add(ModifiableObservableListBase.java:155)
	at java.util.AbstractList.add(AbstractList.java:108)
	at com.speedment.tool.core.internal.component.UserInterfaceComponentImpl.showNotification(UserInterfaceComponentImpl.java:669)
	at com.speedment.tool.core.internal.component.UserInterfaceComponentImpl.showNotification(UserInterfaceComponentImpl.java:664)
	at com.speedment.tool.core.internal.component.UserInterfaceComponentImpl.showNotification(UserInterfaceComponentImpl.java:659)
	at com.speedment.tool.core.internal.component.UserInterfaceComponentImpl.lambda$start$2(UserInterfaceComponentImpl.java:179)
	at com.speedment.common.logger.internal.AbstractLogger.lambda$log$5(AbstractLogger.java:455)
	at java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4649)
	at java.util.Collections$SetFromMap.forEach(Collections.java:5476)
	at com.speedment.common.logger.internal.AbstractLogger.log(AbstractLogger.java:455)
	at com.speedment.common.logger.internal.AbstractLogger.log(AbstractLogger.java:422)
	at com.speedment.common.logger.internal.AbstractLogger.error(AbstractLogger.java:343)
	at com.speedment.common.logger.internal.SystemOutLogger.error(SystemOutLogger.java:25)
	at com.speedment.runtime.core.internal.component.ConnectionPoolComponentImpl.newConnection(ConnectionPoolComponentImpl.java:122)
	at com.speedment.runtime.core.internal.component.ConnectionPoolComponentImpl.getConnection(ConnectionPoolComponentImpl.java:95)
	at com.speedment.runtime.core.internal.component.ConnectionPoolComponentImpl.getConnection(ConnectionPoolComponentImpl.java:79)
	at com.speedment.runtime.core.internal.db.AbstractDbmsMetadataHandler.getConnection(AbstractDbmsMetadataHandler.java:779)
	at com.speedment.runtime.core.internal.db.AbstractDbmsMetadataHandler.lambda$readSchemaMetadata$4(AbstractDbmsMetadataHandler.java:171)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	... 5 more
</pre>

**Comment by Pyknic** [comment]
This is likely a concurrency issue with one of the observable lists in the UI. I'll fix it directly.

**Comment by minborg** [comment]
Another error:
<pre>
java.util.concurrent.CompletionException: com.speedment.runtime.core.exception.SpeedmentException: An exception occured while the tables were loading.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:824)
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.speedment.runtime.core.exception.SpeedmentException: An exception occured while the tables were loading.
	at com.speedment.runtime.core.internal.db.AbstractDbmsMetadataHandler.lambda$null$8(AbstractDbmsMetadataHandler.java:249)
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
	... 6 more
Caused by: java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:659)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	... 5 more
Caused by: java.lang.NullPointerException
	at javafx.collections.ListChangeBuilder.insertAdd(ListChangeBuilder.java:147)
	at javafx.collections.ListChangeBuilder.nextAdd(ListChangeBuilder.java:254)
	at javafx.collections.ObservableListBase.nextAdd(ObservableListBase.java:179)
	at javafx.collections.ModifiableObservableListBase.add(ModifiableObservableListBase.java:153)
	at java.util.AbstractList.add(AbstractList.java:108)
	at com.speedment.tool.core.internal.component.UserInterfaceComponentImpl.lambda$start$2(UserInterfaceComponentImpl.java:167)
	at com.speedment.common.logger.internal.AbstractLogger.lambda$log$5(AbstractLogger.java:455)
	at java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4649)
	at java.util.Collections$SetFromMap.forEach(Collections.java:5476)
	at com.speedment.common.logger.internal.AbstractLogger.log(AbstractLogger.java:455)
	at com.speedment.common.logger.internal.AbstractLogger.log(AbstractLogger.java:422)
	at com.speedment.common.logger.internal.AbstractLogger.warn(AbstractLogger.java:288)
	at com.speedment.common.logger.internal.SystemOutLogger.warn(SystemOutLogger.java:25)
	at com.speedment.runtime.core.internal.db.metadata.ColumnMetaDataImpl.readSilent(ColumnMetaDataImpl.java:134)
	at com.speedment.runtime.core.internal.db.metadata.ColumnMetaDataImpl.<init>(ColumnMetaDataImpl.java:82)
	at com.speedment.runtime.core.db.metadata.ColumnMetaData.of(ColumnMetaData.java:276)
	at com.speedment.runtime.core.internal.db.AbstractDbmsMetadataHandler.lambda$columns$15(AbstractDbmsMetadataHandler.java:345)
	at com.speedment.runtime.core.internal.db.AbstractDbmsMetadataHandler.tableChilds(AbstractDbmsMetadataHandler.java:557)
	at com.speedment.runtime.core.internal.db.AbstractDbmsMetadataHandler.tableChilds(AbstractDbmsMetadataHandler.java:524)
	at com.speedment.runtime.core.internal.db.AbstractDbmsMetadataHandler.columns(AbstractDbmsMetadataHandler.java:413)
	at com.speedment.runtime.core.internal.db.AbstractDbmsMetadataHandler.lambda$null$10(AbstractDbmsMetadataHandler.java:318)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
	... 6 more

</pre>

**Comment by minborg** [comment]
Fixed by introducing synchronized method
