### ISSUE TITLE
Get expiation when generating new table in existing database MariaDB

### ISSUE THREAD

**Issue by rossii123** [speedment/speedment#345]
```
java.lang.NullPointerException
	at com.speedment.maven.component.MavenPathComponent.baseDir(MavenPathComponent.java:43)
	at com.speedment.maven.component.MavenPathComponent.packageLocation(MavenPathComponent.java:49)
	at com.speedment.generator.core.internal.translator.TranslatorManagerImpl.clearExistingFiles(TranslatorManagerImpl.java:135)
	at com.speedment.generator.core.internal.translator.TranslatorManagerImpl.accept(TranslatorManagerImpl.java:117)
	at com.speedment.tool.core.internal.util.ConfigFileHelper.generateSources(ConfigFileHelper.java:372)
	at com.speedment.tool.core.internal.component.UserInterfaceComponentImpl.lambda$generate$8(UserInterfaceComponentImpl.java:357)
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by Pyknic** [comment]
We need to verify that the bug is now fixed.
