### ISSUE TITLE
Incompatible default JDBC driver for PostgreSQL 9.6 in speed maven plugin

### ISSUE THREAD

**Issue by indyaah** [speedment/speedment#366]
Details regarding PostgreSQL change and JDBC driver : pgjdbc/pgjdbc#560

```
2017-03-05T09:16:01.560Z WARN  [ForkJoinPool.commonPool-worker-3] (c.s.r.c.i.d.AbstractDbmsMetadataHandler) - Unable to determine mapping for table social_detail, column detail. Fall-back to JDBC-type Object
2017-03-05T09:16:01.561Z ERROR [ForkJoinPool.commonPool-worker-3] (c.s.r.c.i.d.AbstractDbmsMetadataHandler) - Unable to read table child.
org.postgresql.util.PSQLException: ERROR: column am.amcanorder does not exist
  Position: 427
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1911)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:645)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:481)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:361)
	at org.postgresql.jdbc2.AbstractJdbc2DatabaseMetaData.getIndexInfo(AbstractJdbc2DatabaseMetaData.java:4230)
	at com.speedment.runtime.core.internal.db.AbstractDbmsMetadataHandler.lambda$indexes$19(AbstractDbmsMetadataHandler.java:453)
	at com.speedment.runtime.core.internal.db.AbstractDbmsMetadataHandler.tableChilds(AbstractDbmsMetadataHandler.java:545)
	at com.speedment.runtime.core.internal.db.AbstractDbmsMetadataHandler.indexes(AbstractDbmsMetadataHandler.java:488)
	at com.speedment.runtime.core.internal.db.AbstractDbmsMetadataHandler.lambda$null$10(AbstractDbmsMetadataHandler.java:323)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by indyaah** [comment]
Demo project (literally nothing extra-ordinary except for different configuration for maven-plugin on different branch) : github.com/indyaah/speedment-postgrsql-jdbc
