### ISSUE TITLE
Error building Speedment in JDK 9

### ISSUE THREAD

**Issue by Pyknic** [speedment/speedment#370]
There is a problem when running the tests for Speedment in JDK 9.

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.speedment.generator.TranslatorManagerTest
2017-03-06T22:41:50.610835Z INFO  [main] (c.s.c.i.i.InjectorBuilderImpl) - No configuration file '/home/travis/build/speedment/speedment/generator-parent/generator-core/settings.properties' found.
2017-03-06T22:41:51.602901Z INFO  [main] (c.s.c.i.i.InjectorBuilderImpl) - No configuration file '/home/travis/build/speedment/speedment/generator-parent/generator-core/settings.properties' found.
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 2.33 sec <<< FAILURE! - in com.speedment.generator.TranslatorManagerTest
testPreview(com.speedment.generator.TranslatorManagerTest)  Time elapsed: 1.116 sec  <<< ERROR!
java.lang.NoClassDefFoundError: javax/annotation/Generated
	at com.speedment.common.codegen.constant.DefaultAnnotationUsage.<clinit>(DefaultAnnotationUsage.java:51)
	at com.speedment.generator.standard.entity.GeneratedEntityTranslator.makeCodeGenModel(GeneratedEntityTranslator.java:102)
	at com.speedment.generator.standard.entity.GeneratedEntityTranslator.makeCodeGenModel(GeneratedEntityTranslator.java:73)
	at com.speedment.generator.translator.AbstractJavaClassTranslator.get(AbstractJavaClassTranslator.java:143)
	at com.speedment.generator.translator.AbstractJavaClassTranslator.get(AbstractJavaClassTranslator.java:61)
	at com.speedment.generator.translator.Translator.generate(Translator.java:210)
	at com.speedment.generator.translator.Translator.toCode(Translator.java:222)
	at com.speedment.generator.TranslatorManagerTest.testPreview(TranslatorManagerTest.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:547)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: java.lang.ClassNotFoundException: javax.annotation.Generated
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:533)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:186)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:476)
	... 33 more
```

It appears to be related to the use of `javax.annotation.Generated`, as described [in the following post](https://bugs.openjdk.java.net/browse/JDK-8152842?focusedCommentId=13940962&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13940962):

> As of jdk-9+118, both javac and runtime implement the policy for root modules that is described in JEP 261. As part of this, the javac launcher was changed so that it runs with `-addmods ALL-DEFAULT`. This means the runtime environment when annotation processors execute has all of the non-EE modules. Annotation processors that make use of types in any of the 6 EE modules will need to invoke javac with `-J-addmods -J<module>`. 
> 
> Note that the policy for root modules will be re-evaulated later in JDK 9. In the mean-time then I think we can close this issue as there isn't anything to do.

**Comment by Pyknic** [comment]
Maybe we should stop using the `Generated` annotation since it comes from the Java EE packages and instead either create our own or stop annotating generated classes completely.

**Comment by minborg** [comment]
Changed Generated to the Speedment GeneraedCode annotation.
