### ISSUE TITLE
Error persisting two rows in MariaDB

### ISSUE THREAD

**Issue by rossii123** [speedment/speedment#408]
When persisting two rows directly after each other, the first one succeeds and the second one fails. Running MariaDB.

```sql
CREATE TABLE demo (
`id` varchar(50) NOT NULL,
PRIMARY KEY (`id`)
);
```

```java
TestProjectApplication app = new TestProjectApplicationBuilder()
    .withPassword("password")
    .build();

DemoManager demos = app.getOrThrow(DemoManager.class);
Demo demo = new DemoImpl()
    .setId("hej");
demos.persist(demo);

Demo demo2 = new DemoImpl()
    .setId("hej2");
demos.persist(demo2); // Exception here
```

```
Exception in thread "main" com.speedment.runtime.core.exception.SpeedmentException: java.sql.SQLException: Operation not permit on a closed resultSet
	at com.speedment.runtime.core.internal.component.sql.SqlPersistenceImpl.persist(SqlPersistenceImpl.java:186)
	at com.speedment.runtime.core.internal.component.sql.SqlPersistanceComponentImpl.lambda$persister$0(SqlPersistanceComponentImpl.java:67)
	at com.speedment.runtime.core.manager.AbstractManager.persist(AbstractManager.java:114)
	at com.github.rossii123.mappingtest.sqlmapper.SetupDatabase.main(SetupDatabase.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.sql.SQLException: Operation not permit on a closed resultSet
	at org.mariadb.jdbc.internal.queryresults.resultset.MariaSelectResultSet.next(MariaSelectResultSet.java:535)
	at com.speedment.runtime.core.internal.db.AbstractDbmsOperationHandler.handleSqlStatement(AbstractDbmsOperationHandler.java:236)
	at com.speedment.runtime.core.internal.db.AbstractDbmsOperationHandler.execute(AbstractDbmsOperationHandler.java:163)
	at com.speedment.runtime.core.internal.db.AbstractDbmsOperationHandler.executeInsert(AbstractDbmsOperationHandler.java:126)
	at com.speedment.runtime.core.internal.component.sql.SqlPersistenceImpl.persist(SqlPersistenceImpl.java:183)
	... 8 more
```

**Comment by minborg** [comment]
Unable to reproduce the error. What JDBC version are you using?

**Comment by minborg** [comment]
There was a beginners mistake in the old JDBC driver for MariaDB. Speedment users should use a newer version.
