### ISSUE TITLE
COLLATION 'utf8_bin' is not valid for CHARACTER SET 'utf8mb4'

### ISSUE THREAD

**Issue by fablue** [speedment/speedment#481]
Getting the title error on my linux machine. Works great with the windows test-server on the same database (cloned) and the same code. 

I am using utf8mb4_general_ci as standard collation, but utf8mb4_bin at column "token". 
I think the part ```(`lime`.`user`.`token`  = ? COLLATE utf8_bin)``` should use utf8mb4_bin instead?
Interestingly enough: It does not help when I convert the column token to utf8_bin!

## Stacktrace
```
2017-06-08T18:10:42.336Z INFO  [http-nio-8080-exec-1] (#APPLICATION_BUILDER) - Speedment (Open Source) version 3.0.10 by Speedment, Inc. Specification version 3.0
2017-06-08T18:10:42.336Z INFO  [http-nio-8080-exec-1] (#APPLICATION_BUILDER) - Java Platform API Specification 1.8 by Oracle Corporation. Implementation N/A 1.8.0_131 by N/A
2017-06-08T18:10:42.655Z INFO  [http-nio-8080-exec-1] (#APPLICATION_BUILDER) - MySQL, 10.0.29-MariaDB-0ubuntu0.16.10.1, MariaDB connector/J 2.0.2, JDBC version 4.2
2017-06-08T18:10:42.852Z ERROR [http-nio-8080-exec-3] (c.s.r.c.i.d.AsynchronousQueryResultImpl) - Error executing SELECT `id`,`token`,`firebase`,`initial`,`timestamp_location`,`distance`,`longitude`,`latitude` FROM `lime`.`user` WHERE (`lime`.`user`.`token`  = ? COLLATE utf8_bin), values=[sometoken]
java.sql.SQLSyntaxErrorException: (conn:18774) COLLATION 'utf8_bin' is not valid for CHARACTER SET 'utf8mb4'
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:158)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:245)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:218)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:153)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeQuery(MariaDbPreparedStatementClient.java:167)
	at com.speedment.runtime.core.internal.db.AsynchronousQueryResultImpl.stream(AsynchronousQueryResultImpl.java:95)
	at com.speedment.runtime.core.internal.component.sql.SqlStreamSupplierImpl.lambda$stream$6(SqlStreamSupplierImpl.java:184)
	at com.speedment.runtime.core.internal.stream.builder.pipeline.PipelineImpl.getStream(PipelineImpl.java:85)
	at com.speedment.runtime.core.internal.stream.builder.pipeline.PipelineImpl.getAsReferenceStream(PipelineImpl.java:63)
	at com.speedment.runtime.core.internal.component.sql.override.def.reference.DefaultFindAnyTerminator.apply(DefaultFindAnyTerminator.java:45)
	at com.speedment.runtime.core.internal.manager.sql.SqlStreamTerminator.findAny(SqlStreamTerminator.java:176)
	at com.speedment.runtime.core.internal.stream.builder.ReferenceStreamBuilder.lambda$findAny$16(ReferenceStreamBuilder.java:406)
	at com.speedment.runtime.core.internal.stream.builder.AbstractStreamBuilder.finallyCloseReference(AbstractStreamBuilder.java:189)
	at com.speedment.runtime.core.internal.stream.builder.ReferenceStreamBuilder.findAny(ReferenceStreamBuilder.java:406)
```
## Database
![image](https://user-images.githubusercontent.com/10995950/26944811-174bdf1c-4c8a-11e7-8047-e2ae47de2cc8.png)

![image](https://user-images.githubusercontent.com/10995950/26944844-2788ba76-4c8a-11e7-8d55-af1160946e6d.png)

**Comment by Pyknic** [comment]
I think you are right, it should be `utf8mb4_bin` for `utf8mb4`-columns and `utf8_bin` for `utf8`-columns. The problem is that we currently don't know the collation when we generate the SQL statement. We could probably collect that information when we scan the metadata, but it will require some work on the metadata handler.

**Comment by fablue** [comment]
Is there any way for me to get this up and running? Changing the column to utf8_bin did not work for me =(

**Comment by minborg** [comment]
It is truly strange. It might be the case that there are different defaults for the table collation. Try to re-create your table using "utf8" . We do our integration tests on Linux and here is one example of a table created for MariaDB:
```
CREATE TABLE `user` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(45) NOT NULL,
  `surname` varchar(45) NOT NULL,
  `email` varchar(45) NOT NULL,
  `password` varchar(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `Index_email` (`email`),
  KEY `Index_name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=utf8;
```

**Comment by fablue** [comment]
Re-creating the table with ut8 might not solve the problem because I do rely on uf8mb4 because of emoji. Seems like I have to downgrade my Speedment version until this is fixed? 
😢

**Comment by minborg** [comment]
I will take a look at it tomorrow.

**Comment by minborg** [comment]
Working on this issue now. I saw this post that might help you understand server side issues with utfmb4 https://mathiasbynens.be/notes/mysql-utf8mb4#utf8-to-utf8mb4

**Comment by fablue** [comment]
Oh thank you 👍

**Comment by minborg** [comment]
This is how you fix the problem: https://speedment.github.io/speedment-doc/connectors.html#mariadb

Let me know if it works for you (once we have released 3.0.11)

**Comment by fablue** [comment]
Thank you very much! This is awesome ☺️

**Comment by fablue** [comment]
I am really confused right now:
It is working on my Linux production server, but it tells me the following on my Windows machine, 
even though it is the exact same table containing the exact same data and having the exact same collations!

```
Caused by: java.sql.SQLException: COLLATION 'utf8mb4_bin' is not valid for CHARACTER SET 'utf8'
```

**Comment by fablue** [comment]
Fixed by adding the following to my.ini

```
character-set-server  = utf8mb4
collation-server      = utf8mb4_general_ci

```

**Comment by minborg** [comment]
@fablue Great that you manage to get it working!

**Comment by Pyknic** [comment]
This is a very common issue so I thought I'd post a workaround. If you get the exception posted above you can solve it by adding the following to your Speedment Application Builder:

```java
SakilaApplication app = new SakilaApplicationBuilder()
     // The following two lines:
    .withParam("db.mysql.collationName", "utf8mb4_general_ci")
    .withParam("db.mysql.binaryCollationName", "utf8mb4_bin")
    .build();
```
