### ISSUE TITLE
Is this a bug? Why can't my database appear behind “3306/?

### ISSUE THREAD

**Issue by jx-qyj** [speedment/speedment#482]
java.util.concurrent.CompletionException: com.speedment.runtime.core.exception.SpeedmentException: Unable to get connection using url "jdbc:mysql://127.0.0.1F:3306/?useUnicode=true&characterEncoding=UTF-8&useServerPrepStmts=true&zeroDateTimeBehavior=convertToNull&useSSL=false&nullNamePatternMatchesAll=true&useLegacyDatetimeCode=true", user = "root", password = "********".
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1621)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.speedment.runtime.core.exception.SpeedmentException: Unable to get connection using url "jdbc:mysql://127.0.0.1F:3306/?useUnicode=true&characterEncoding=UTF-8&useServerPrepStmts=true&zeroDateTimeBehavior=convertToNull&useSSL=false&nullNamePatternMatchesAll=true&useLegacyDatetimeCode=true", user = "root", password = "********".
	at com.speedment.runtime.core.internal.component.ConnectionPoolComponentImpl.newConnection(ConnectionPoolComponentImpl.java:132)
	at com.speedment.runtime.core.internal.component.ConnectionPoolComponentImpl.getConnection(ConnectionPoolComponentImpl.java:99)
	at com.speedment.runtime.core.internal.component.ConnectionPoolComponentImpl.getConnection(ConnectionPoolComponentImpl.java:79)
	at com.speedment.runtime.core.internal.db.AbstractDbmsMetadataHandler.getConnection(AbstractDbmsMetadataHandler.java:807)
	at com.speedment.runtime.core.internal.db.AbstractDbmsMetadataHandler.lambda$readSchemaMetadata$4(AbstractDbmsMetadataHandler.java:176)
	at com.speedment.runtime.core.internal.db.AbstractDbmsMetadataHandler$$Lambda$620/1979726124.run(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618)
	... 5 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.GeneratedConstructorAccessor35.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:989)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:341)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2203)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2236)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2035)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:790)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor33.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.speedment.runtime.core.internal.component.ConnectionPoolComponentImpl.newConnection(ConnectionPoolComponentImpl.java:123)
	... 11 more
Caused by: java.net.UnknownHostException: 127.0.0.1F
	at java.net.InetAddress.getAllByName0(InetAddress.java:1259)
	at java.net.InetAddress.getAllByName(InetAddress.java:1171)
	at java.net.InetAddress.getAllByName(InetAddress.java:1105)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:188)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300)
	... 25 more

**Comment by Pyknic** [comment]
I think the problem is the ip `127.0.0.1F`. If it is a local MySQL database then it should probably be `127.0.0.1`.
