### ISSUE TITLE
java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by muhdkhokhar** [speedment/speedment#588]
I am getting 

java.lang.UnsupportedOperationException

When I try to generate code from postgres 10 

**Full stack trace**

java.lang.UnsupportedOperationException
	at java.util.Collections$UnmodifiableMap.put(Collections.java:1457)
	at com.speedment.generator.standard.lifecycle.GeneratedMetadataTranslator.makeCodeGenModel(GeneratedMetadataTranslator.java:78)
	at com.speedment.generator.standard.lifecycle.GeneratedMetadataTranslator.makeCodeGenModel(GeneratedMetadataTranslator.java:46)
	at com.speedment.generator.translator.AbstractJavaClassTranslator.get(AbstractJavaClassTranslator.java:144)
	at com.speedment.generator.translator.AbstractJavaClassTranslator.get(AbstractJavaClassTranslator.java:62)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.speedment.generator.core.internal.translator.TranslatorManagerHelper.accept(TranslatorManagerHelper.java:142)
	at com.speedment.generator.core.internal.translator.DefaultTranslatorManager.accept(DefaultTranslatorManager.java:58)
	at com.speedment.tool.core.internal.util.ConfigFileHelper.generateSources(ConfigFileHelper.java:416)
	at com.speedment.tool.core.internal.component.UserInterfaceComponentImpl.lambda$generate$10(UserInterfaceComponentImpl.java:358)
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by minborg** [comment]
ok. Thanks. I have scheduled this issue to release 3.0.22

**Comment by minborg** [comment]
Can you upload the `speedment.json` file for your project to this issue?

**Comment by muhdkhokhar** [comment]
speedment.json file uploaded as requested
[speedment.zip](https://github.com/speedment/speedment/files/1717795/speedment.zip)

**Comment by minborg** [comment]
Thanks

**Comment by Pyknic** [comment]
I think I can see the problem. It is a bug introduced when we added a version check to make sure the code is executed with the same version of Speedment as it was generated with. 

I will fix this now and make sure it is included in the `3.0.22`-release. Until then, you can either go back to `3.0.20` that doesn't have this issue or build Speedment `3.0.22-SNAPSHOT` yourself by checking out the `develop-3.0`-branch.

**Comment by Pyknic** [comment]
Hm, it didn't fis the problem entirely. It seems to be related to generating code from the tool. Using `mvn speedment:generate` seems to work.

**Comment by Pyknic** [comment]
I have fixed this now. I can verify that I get the same exception with `3.0.21` and it doesn't show up in `3.0.22-SNAPSHOT`. We should do an immediate release of `3.0.22` since this will affect most users.
