### ISSUE TITLE
postgres blob issue 

### ISSUE THREAD

**Issue by muhdkhokhar** [speedment/speedment#596]
I have column byteea in postgres table speedment coverts to Optional<Blob>

When I stream data i get error 

com.speedment.runtime.core.exception.SpeedmentException: org.postgresql.util.PSQLException: Bad value for type long : \x230d0a23546875204665622030382031383a35353a323720474d5420323031380d0a6d794b65793d6d7956616c75650d0a

**Full stack trace**

2018-02-17T12:57:28.227Z ERROR [main] (c.s.r.c.i.s.b.AbstractStreamBuilder) - org.postgresql.util.PSQLException: Bad value for type long : \x230d0a23546875204665622030382031383a35353a323720474d5420323031380d0a6d794b65793d6d7956616c75650d0a
com.speedment.runtime.core.exception.SpeedmentException: org.postgresql.util.PSQLException: Bad value for type long : \x230d0a23546875204665622030382031383a35353a323720474d5420323031380d0a6d794b65793d6d7956616c75650d0a
	at com.company.public_.scheduledemo.public_.qrtz_job_details.generated.GeneratedQrtzJobDetailsSqlAdapter.apply(GeneratedQrtzJobDetailsSqlAdapter.java:56)
	at com.speedment.runtime.core.internal.stream.StreamUtil$ResultSetIterator.forEachRemaining(StreamUtil.java:196)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at com.speedment.runtime.core.internal.component.sql.override.def.reference.DefaultForEachTerminator.apply(DefaultForEachTerminator.java:47)
	at com.speedment.runtime.core.internal.manager.sql.SqlStreamTerminator.forEach(SqlStreamTerminator.java:101)
	at com.speedment.runtime.core.internal.stream.builder.ReferenceStreamBuilder.lambda$forEach$0(ReferenceStreamBuilder.java:165)
	at com.speedment.runtime.core.internal.stream.builder.AbstractStreamBuilder.finallyClose(AbstractStreamBuilder.java:178)
	at com.speedment.runtime.core.internal.stream.builder.ReferenceStreamBuilder.forEach(ReferenceStreamBuilder.java:165)
	at com.company.public_.Test.main(Test.java:18)
Caused by: org.postgresql.util.PSQLException: Bad value for type long : \x230d0a23546875204665622030382031383a35353a323720474d5420323031380d0a6d794b65793d6d7956616c75650d0a
	at org.postgresql.jdbc.PgResultSet.toLong(PgResultSet.java:2859)
	at org.postgresql.jdbc.PgResultSet.getLong(PgResultSet.java:2113)
	at org.postgresql.jdbc.PgResultSet.getBlob(PgResultSet.java:417)
	at com.company.public_.scheduledemo.public_.qrtz_job_details.generated.GeneratedQrtzJobDetailsSqlAdapter.apply(GeneratedQrtzJobDetailsSqlAdapter.java:54)
	... 9 more

Process finished with exit code 1

**Comment by minborg** [comment]
Please upload the `speedment.json` file in your project to this issue so we can reproduce the error.

**Comment by muhdkhokhar** [comment]
File attached
[speedment.zip](https://github.com/speedment/speedment/files/1734617/speedment.zip)

**Comment by julgus** [comment]
Can you please provide me with the SQL CREATE TABLE statement for that particular table.

**Comment by muhdkhokhar** [comment]
create table qrtz_job_details
  (
    sched_name varchar(120) not null,
    job_name  varchar(200) not null,
    job_group varchar(200) not null,
    description varchar(250) null,
    job_class_name   varchar(250) not null,
    is_durable bool not null,
    is_nonconcurrent bool not null,
    is_update_data bool not null,
    requests_recovery bool not null,
    job_data bytea null,
    primary key (sched_name,job_name,job_group)
);

**Comment by julgus** [comment]
Thank you, as you pointed out it's the job_data column that causes the error. Currently, Speedment doesn't support the mapping of a bytea to a blob. 

There are a few possible options to work around this issue: 
1) To create your own map from bytea to blob. 
2) Express the value as a String and parse it manually. 
3) Or lastly, change the column type to a valid type.

**Comment by muhdkhokhar** [comment]
OK thanks . I'll update it.
