### ISSUE TITLE
Wrong JDBC-connector is used by Maven Plugin

### ISSUE THREAD

**Issue by Pyknic** [speedment/speedment#616]
When connecting to a MySQL database, it seems like the MariaDB-connector is used even if you select "MySQL" in the tool and explicetly specify the MySQL JDBC connector in the pom.xml-file. This is a problem since the latest MariaDB connector is not compatible with a modern MySQL database.

```
2018-04-23T16:41:35.580738Z ERROR [ForkJoinPool.commonPool-worker-2] (#CONNECTION) - Unable to get connection using url "jdbc:mysql://127.0.0.1:3306?useUnicode=true&characterEncoding=UTF-8&useServerPrepStmts=true&useSSL=false&zeroDateTimeBehavior=convertToNull&nullNamePatternMatchesAll=true&useLegacyDatetimeCode=true", user = "root", password = "********".
java.sql.SQLNonTransientConnectionException: Client does not support authentication protocol requested by server. Consider upgrading MariaDB client. plugin was = caching_sha2_password
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:175)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:110)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1088)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:493)
	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:150)
	at org.mariadb.jdbc.Driver.connect(Driver.java:86)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.speedment.runtime.core.internal.component.ConnectionPoolComponentImpl.newConnection(ConnectionPoolComponentImpl.java:123)
	at com.speedment.runtime.core.internal.component.ConnectionPoolComponentImpl.getConnection(ConnectionPoolComponentImpl.java:99)
	at com.speedment.runtime.core.internal.component.ConnectionPoolComponentImpl.getConnection(ConnectionPoolComponentImpl.java:79)
	at com.speedment.runtime.core.internal.db.AbstractDbmsMetadataHandler.getConnection(AbstractDbmsMetadataHandler.java:837)
	at com.speedment.runtime.core.internal.db.AbstractDbmsMetadataHandler.readTypeMapFromDB(AbstractDbmsMetadataHandler.java:730)
	at com.speedment.runtime.core.internal.db.AbstractDbmsMetadataHandler.lambda$readSchemaMetadata$4(AbstractDbmsMetadataHandler.java:185)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1603)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.sql.SQLException: Client does not support authentication protocol requested by server. Consider upgrading MariaDB client. plugin was = caching_sha2_password
	at org.mariadb.jdbc.internal.protocol.authentication.DefaultAuthenticationProvider.processAuthPlugin(DefaultAuthenticationProvider.java:100)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:829)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:775)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:453)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1084)
	... 16 more
```

**Comment by Pyknic** [comment]
Workaround:
First, specify the MySQL JDBC dependency as a dependency to the speedment-maven-plugin:
```xml
<plugin>
    <groupId>com.speedment</groupId>
    <artifactId>speedment-maven-plugin</artifactId>
    <version>${speedment.version}</version>

    <dependencies>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.11</version>
            <scope>runtime</scope>
        </dependency>
    </dependencies>
</plugin>
```

When the Speedment tool launches, you need to change two things in the "connection URL"-field before connecting:
1. Add `&serverTimezone=UTC` to the end
2. Change the value `&zeroDateTimeBehavior=` to `CONVERT_TO_NULL` (the old camel case spelling does no longer work)

**Comment by lawesson** [comment]
Even after adding the connector as described in the workaround the tests may fail since the driver is fetched via the connection URL matching also MariaDB. The proper fix seems to be to remove the bundled jdbc drivers from the maven plugin. This would require the initalizer to add the JDBC dependency to the plugin as well as a runtime dependency in the pom since the URL Class loader of the maven plugin seems to fail to find the class via the project runtime dependency. Suggestion:

1. Remove bundled JDBC drivers from the maven plugin
2. Make the initializer add explicit JDBC dependency to the maven plugin (as it currently does for, e.g., oracle) for all databases.
