### ISSUE TITLE
Exception during connection

### ISSUE THREAD

**Issue by Pyknic** [speedment/speedment#621]
```
java.sql.SQLNonTransientConnectionException: Public Key Retrieval is not allowed
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:108)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:95)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:862)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:444)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:230)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:226)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.speedment.runtime.core.internal.component.ConnectionPoolComponentImpl.newConnection(ConnectionPoolComponentImpl.java:123)
	at com.speedment.runtime.core.internal.component.ConnectionPoolComponentImpl.getConnection(ConnectionPoolComponentImpl.java:99)
	at com.speedment.runtime.core.internal.component.ConnectionPoolComponentImpl.getConnection(ConnectionPoolComponentImpl.java:79)
	at com.speedment.runtime.core.internal.db.AbstractDbmsMetadataHandler.getConnection(AbstractDbmsMetadataHandler.java:837)
	at com.speedment.runtime.core.internal.db.AbstractDbmsMetadataHandler.getDbmsInfoString(AbstractDbmsMetadataHandler.java:143)
	at com.speedment.runtime.core.internal.AbstractApplicationBuilder.lambda$checkDatabaseConnectivity$20(AbstractApplicationBuilder.java:444)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1239)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:502)
	at com.speedment.runtime.core.internal.AbstractApplicationBuilder.checkDatabaseConnectivity(AbstractApplicationBuilder.java:433)
	at com.speedment.runtime.core.internal.AbstractApplicationBuilder.build(AbstractApplicationBuilder.java:383)
	at com.speedment.example.jforum2018.sakila.SakilaApplication.startSpeedment(SakilaApplication.java:20)
	at REPL.$JShell$16.do_it$($JShell$16.java:6)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at jdk.jshell/jdk.jshell.execution.DirectExecutionControl.invoke(DirectExecutionControl.java:209)
	at jdk.jshell/jdk.jshell.execution.RemoteExecutionControl.invoke(RemoteExecutionControl.java:116)
	at jdk.jshell/jdk.jshell.execution.DirectExecutionControl.invoke(DirectExecutionControl.java:119)
	at jdk.jshell/jdk.jshell.execution.ExecutionControlForwarder.processCommand(ExecutionControlForwarder.java:144)
	at jdk.jshell/jdk.jshell.execution.ExecutionControlForwarder.commandLoop(ExecutionControlForwarder.java:237)
	at jdk.jshell/jdk.jshell.execution.Util.forwardExecutionControl(Util.java:76)
	at jdk.jshell/jdk.jshell.execution.Util.forwardExecutionControlAndIO(Util.java:137)
	at jdk.jshell/jdk.jshell.execution.RemoteExecutionControl.main(RemoteExecutionControl.java:70)

|  com.speedment.runtime.core.exception.SpeedmentException thrown: Unable to get connection using url "jdbc:mysql://127.0.0.1:3306?useUnicode=true&characterEncoding=UTF-8&useServerPrepStmts=true&useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL&nullNamePatternMatchesAll=true&useLegacyDatetimeCode=true&serverTimezone=UTC", user = "root", password = "********".
|        at ConnectionPoolComponentImpl.newConnection (ConnectionPoolComponentImpl.java:132)
|        at ConnectionPoolComponentImpl.getConnection (ConnectionPoolComponentImpl.java:99)
|        at ConnectionPoolComponentImpl.getConnection (ConnectionPoolComponentImpl.java:79)
|        at AbstractDbmsMetadataHandler.getConnection (AbstractDbmsMetadataHandler.java:837)
|        at AbstractDbmsMetadataHandler.getDbmsInfoString (AbstractDbmsMetadataHandler.java:143)
|        at AbstractApplicationBuilder.lambda$checkDatabaseConnectivity$20 (AbstractApplicationBuilder.java:444)
|        at ForEachOps$ForEachOp$OfRef.accept (ForEachOps.java:183)
|        at ReferencePipeline$3$1.accept (ReferencePipeline.java:195)
|        at LinkedList$LLSpliterator.forEachRemaining (LinkedList.java:1239)
|        at AbstractPipeline.copyInto (AbstractPipeline.java:484)
|        at AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:474)
|        at ForEachOps$ForEachOp.evaluateSequential (ForEachOps.java:150)
|        at ForEachOps$ForEachOp$OfRef.evaluateSequential (ForEachOps.java:173)
|        at AbstractPipeline.evaluate (AbstractPipeline.java:234)
|        at ReferencePipeline.forEachOrdered (ReferencePipeline.java:502)
|        at AbstractApplicationBuilder.checkDatabaseConnectivity (AbstractApplicationBuilder.java:433)
|        at AbstractApplicationBuilder.build (AbstractApplicationBuilder.java:383)
|        at SakilaApplication.startSpeedment (SakilaApplication.java:20)
|        at (#6:1)

```

**Comment by Pyknic** [comment]
This error is a bit spurious, but it seems to be related to the JVM not having the public key of the MySQL server, so it throws an exception. As soon as it has the public key, it will work even if the JVM is restarted, don't ask me why. However, I don't see any problem always adding `allowPublicKeyRetrieval=true` to the connection URL, so I suggest we do that.
