### ISSUE TITLE
Join: joinComponent uses javaName instead of databaseName

### ISSUE THREAD

**Issue by Pyknic** [speedment/speedment#651]
When joining on a table where the `javaName` and `databaseName` differs, you get an exception.

```
Exception in thread "main" java.lang.IllegalStateException: There is no table for table identifier "employees.employees.salaries" for stage index 1 of [0, 1]. These table identifiers are available from previous join stages: employees.employees.salary, employees.employees.employees
	at com.speedment.runtime.join.internal.component.join.AbstractJoinBuilder.stageIndexOf(AbstractJoinBuilder.java:206)
	at com.speedment.runtime.join.internal.component.join.AbstractJoinBuilder.resolveStages(AbstractJoinBuilder.java:172)
	at com.speedment.runtime.join.internal.component.join.AbstractJoinBuilder.stages(AbstractJoinBuilder.java:128)
	at com.speedment.runtime.join.internal.component.join.JoinBuilder2Impl.build(JoinBuilder2Impl.java:82)
	at com.speedment.enterprise.benchmark.joins.Main.main(Main.java:63)
```

Example query:
```java
joins.from(SalaryManager.IDENTIFIER)
    .innerJoinOn(Employee.EMP_NO).equal(Salary.EMP_NO)
    .build(Tuples::of)
```

(The database tables are named `employees` and `salaries`, but they have both been given Speedment Aliases so that they appear as `employee` and `salary` in the generated code)

**Comment by Pyknic** [comment]
This might be caused by #652.
