### ISSUE TITLE
PostgreSQL error in speedment setup

### ISSUE THREAD

**Issue by solangepaz** [speedment/speedment#719]
Hello,
When I am setting up speedment to use PostgreSQL I get this error:
`java.util.concurrent.CompletionException: com.speedment.runtime.core.exception.SpeedmentException: Unable to get connection using url "jdbc:postgresql://127.0.0.1:5432/tpch?stringtype=unspecified", user = "postgres", password = "********".
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1629)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.speedment.runtime.core.exception.SpeedmentException: Unable to get connection using url "jdbc:postgresql://127.0.0.1:5432/tpch?stringtype=unspecified", user = "postgres", password = "********".
	at com.speedment.runtime.core.internal.component.ConnectionPoolComponentImpl.newConnection(ConnectionPoolComponentImpl.java:169)
	at com.speedment.runtime.core.internal.component.ConnectionPoolComponentImpl.getConnection(ConnectionPoolComponentImpl.java:136)
	at com.speedment.runtime.core.internal.component.ConnectionPoolComponentImpl.getConnection(ConnectionPoolComponentImpl.java:113)
	at com.speedment.runtime.core.internal.db.AbstractDbmsMetadataHandler.getConnection(AbstractDbmsMetadataHandler.java:862)
	at com.speedment.runtime.core.internal.db.AbstractDbmsMetadataHandler.lambda$readSchemaMetadata$6(AbstractDbmsMetadataHandler.java:208)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	... 5 more
Caused by: java.sql.SQLException: No suitable driver found for jdbc:postgresql://127.0.0.1:5432/tpch?stringtype=unspecified
	at java.sql.DriverManager.getConnection(DriverManager.java:689)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.speedment.runtime.core.internal.component.ConnectionPoolComponentImpl.newConnection(ConnectionPoolComponentImpl.java:160)
	... 10 more
`
How can I solve it?
Thanks.

**Comment by minborg** [comment]
The text "No suitable driver found for..." indicates that you might not have the Postgres JDBC driver on your classpath. Make sure that you have something like this in your pom:
```
```

**Comment by solangepaz** [comment]
Yes, I have this is my pom:

> `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.speedment.demo</groupId>
    <artifactId>salesinfo</artifactId>
    <version>1.0-SNAPSHOT</version>


    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>com.speedment</groupId>
                <artifactId>speedment-maven-plugin</artifactId>
                <version>3.1.12</version>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>com.speedment</groupId>
            <artifactId>runtime</artifactId>
            <version>3.1.12</version>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.2.2</version>

        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>3.1.12</version>
        </dependency>
    </dependencies>


</project>`

**Comment by minborg** [comment]
ok. I see. You also need to include the `postgresql` dependency together with the `speedment-maven-plugin` as described here: https://speedment.github.io/speedment-doc/maven.html#installation

https://www.speedment.com/initializer/ will always provide a correct POM for your projects.

**Comment by minborg** [comment]
Let me know if this solves your problem.

**Comment by solangepaz** [comment]
The problem is solved, thank you :)

**Comment by minborg** [comment]
Great. Good luck with your project!
