### ISSUE TITLE
How can I change the database that the application uses?

### ISSUE THREAD

**Issue by solangepaz** [speedment/speedment#730]
I wanted to change the database that my application uses, instead of using MySQL data it should use SQLite data.
I've tried this, but it does not work:

```
      Tpch1gApplication app = new Tpch1gApplicationBuilder()
                .withPassword("root")
                .withLogging(ApplicationBuilder.LogType.STREAM_OPTIMIZER)
                .withLogging(ApplicationBuilder.LogType.STREAM)
                .withLogging(ApplicationBuilder.LogType.APPLICATION_BUILDER)
                .withSkipCheckDatabaseConnectivity()
                .withDbms(NationManager.IDENTIFIER, dbms -> dbms.mutator().setTypeName("SQLite"))
                .build();

```

I have this error:
```
Exception in thread "main" com.speedment.runtime.core.exception.SpeedmentException: java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (no such table: nation)
	at com.speedment.runtime.core.internal.db.AbstractDbmsOperationHandler.executeQuery(AbstractDbmsOperationHandler.java:113)
	at com.speedment.runtime.core.internal.component.sql.SqlStreamSupplierImpl.executeAndGetLong(SqlStreamSupplierImpl.java:210)
	at com.speedment.runtime.core.internal.component.sql.override.optimized.util.CountUtil.countHelper(CountUtil.java:65)
	at com.speedment.runtime.core.internal.component.sql.override.optimized.reference.OptimizedCountTerminator.apply(OptimizedCountTerminator.java:45)
	at com.speedment.runtime.core.internal.manager.sql.SqlStreamTerminator.count(SqlStreamTerminator.java:156)
	at com.speedment.runtime.core.internal.stream.builder.ReferenceStreamBuilder.lambda$count$11(ReferenceStreamBuilder.java:333)
	at com.speedment.runtime.core.internal.stream.builder.AbstractStreamBuilder.finallyCloseLong(AbstractStreamBuilder.java:141)
	at com.speedment.runtime.core.internal.stream.builder.ReferenceStreamBuilder.count(ReferenceStreamBuilder.java:333)
	at Main.main(Main.java:20)
```

**Comment by minborg** [comment]
@solangepaz I think you are on the right track with this solution. For SQLite, you need to set the file name of the database. Unfortunately, the method for doing this is missing in the DbmsMutator. I have filed a separate issue (#731) for this. As a workaround until next version, you can do:

```
      Tpch1gApplication app = new Tpch1gApplicationBuilder()
                .withPassword("root")
                .withLogging(ApplicationBuilder.LogType.STREAM_OPTIMIZER)
                .withLogging(ApplicationBuilder.LogType.STREAM)
                .withLogging(ApplicationBuilder.LogType.APPLICATION_BUILDER)
                .withSkipCheckDatabaseConnectivity()
                .withDbms(NationManager.IDENTIFIER, dbms -> dbms.mutator().setTypeName("SQLite"))
                .withDbms(FilmManager.IDENTIFIER, d -> d.mutator().put(Dbms.LOCAL_PATH, "your-file-path"))
                .build();
```


(I assume that you have created the table `nation` in SQLite)

**Comment by solangepaz** [comment]
Thank you, this works. And can not I use the mutator without identifying the table?
Something like:
.withDbms (dbms-> dbms.mutator (). setTypeName ("SQLite"))

**Comment by minborg** [comment]
In the general case, there could be more than one DBMS. So that is the reason you have to give an identifier.
