### ISSUE TITLE
Error parsing date

### ISSUE THREAD

**Issue by solangepaz** [speedment/speedment#741]
I have the speedment configured for MySQL, but when I change to an SQLITE database: 
```
   TpchApplication app = new TpchApplicationBuilder()
              .withPassword("root")
              .withLogging(ApplicationBuilder.LogType.STREAM)
              .withSkipCheckDatabaseConnectivity()
              .withDbms(OrdersManager.IDENTIFIER, dbms -> dbms.mutator().setTypeName("SQLite"))
              .withDbms(OrdersManager.IDENTIFIER, d -> d.mutator().put(Dbms.LOCAL_PATH, "TPC-H.db"))               
              .build();
```
 I have this error:
```
Exception in thread "main" com.speedment.runtime.core.exception.SpeedmentException: java.sql.SQLException: Error parsing date
	at com.speedment.runtime.core.internal.stream.StreamUtil$ResultSetIterator.forEachRemaining(StreamUtil.java:200)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.LongPipeline.reduce(LongPipeline.java:438)
	at java.util.stream.LongPipeline.sum(LongPipeline.java:396)
	at java.util.stream.ReferencePipeline.count(ReferencePipeline.java:526)
	at com.speedment.runtime.core.internal.stream.autoclose.AbstractAutoClosingStream.finallyClose(AbstractAutoClosingStream.java:71)
	at com.speedment.runtime.core.internal.stream.autoclose.AutoClosingReferenceStream.count(AutoClosingReferenceStream.java:198)
	at com.speedment.runtime.join.internal.component.stream.sql.InitialJoinStream.count(InitialJoinStream.java:235)
	at Main.main(Main.java:60)
Caused by: java.sql.SQLException: Error parsing date
	at org.sqlite.jdbc3.JDBC3ResultSet.getDate(JDBC3ResultSet.java:290)
	at com.company.tpch.tpch.tpch.lineitem.generated.GeneratedLineitemSqlAdapter.apply(GeneratedLineitemSqlAdapter.java:45)
	at com.company.tpch.tpch.tpch.lineitem.generated.GeneratedLineitemSqlAdapter.lambda$entityMapper$0(GeneratedLineitemSqlAdapter.java:70)
	at com.speedment.runtime.join.internal.component.stream.sql.SqlHasCreateJoin2.lambda$createJoin$0(SqlHasCreateJoin2.java:58)
	at com.speedment.runtime.core.internal.stream.StreamUtil$ResultSetIterator.forEachRemaining(StreamUtil.java:198)
	... 12 more
Caused by: java.text.ParseException: Unparseable date: "1996-03-30" does not match (\p{Nd}++)\Q-\E(\p{Nd}++)\Q-\E(\p{Nd}++)\Q \E(\p{Nd}++)\Q:\E(\p{Nd}++)\Q:\E(\p{Nd}++)\Q.\E(\p{Nd}++)
	at org.sqlite.date.FastDateParser.parse(FastDateParser.java:299)
	at org.sqlite.date.FastDateFormat.parse(FastDateFormat.java:490)
	at org.sqlite.jdbc3.JDBC3ResultSet.getDate(JDBC3ResultSet.java:287)
	... 16 more
```

**Comment by minborg** [comment]
I think this is a sqlite problem: https://github.com/xerial/sqlite-jdbc/issues/88

There are some tips in the link above. Let me know if that works.

**Comment by minborg** [comment]
Hi @solangepaz 
Did you manage to fix this problem?

**Comment by solangepaz** [comment]
Hi, 
Sorry for the delay, I could not see this before. The problem continues because I do not know how to add this code to speedment:
```
SQLiteConfig sqLiteConfig = new SQLiteConfig();
Properties properties = sqLiteConfig.toProperties();
properties.setProperty(Pragma.DATE_STRING_FORMAT.pragmaName, "yyyy-MM-dd HH:mm:ss");
conn = DriverManager.getConnection("jdbc:sqlite:", properties);
```
Is it possible to add here?
  ```
PostgresApplication app = new PostgresApplicationBuilder()
                 .withPassword("root")
                .withLogging(ApplicationBuilder.LogType.STREAM)
                .withSkipCheckDatabaseConnectivity() 
                .withDbms(NationManager.IDENTIFIER, d->d.mutator().setTypeName("SQLite"))
                .withDbms(NationManager.IDENTIFIER, d->d.mutator().put(Dbms.LOCAL_PATH, "TPC-H_old.db"))
                .build();   

```

**Comment by minborg** [comment]
Is it possible to set properties directly in the connector string? That would be easier to do.
