### ISSUE TITLE
Postgres: JSON types fails under  postgres 12

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#761]
Postgres is stricter with types in later versions. See https://stackoverflow.com/questions/35844138/how-can-i-insert-json-object-into-postgres-using-java-preparedstatement

A work-around is to use `stringtype=unspecified` in the JDBC connection URL/options.

```
org.postgresql.util.PSQLException: ERROR: column "json_support" is of type json but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 267
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440) ~[postgresql-42.2.5.jar:42.2.5]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183) ~[postgresql-42.2.5.jar:42.2.5]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308) ~[postgresql-42.2.5.jar:42.2.5]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441) ~[postgresql-42.2.5.jar:42.2.5]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365) ~[postgresql-42.2.5.jar:42.2.5]
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143) ~[postgresql-42.2.5.jar:42.2.5]
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:120) ~[postgresql-42.2.5.jar:42.2.5]
	at com.speedment.runtime.core.internal.db.AbstractDbmsOperationHandler.handleSqlStatement(AbstractDbmsOperationHandler.java:287) ~[runtime-core-3.1.17.jar:na]
	at com.speedment.runtime.core.internal.db.AbstractDbmsOperationHandler.executeSqlStatementList(AbstractDbmsOperationHandler.java:262) ~[runtime-core-3.1.17.jar:na]
	at com.speedment.runtime.core.internal.db.AbstractDbmsOperationHandler.executeInTransaction(AbstractDbmsOperationHandler.java:245) ~[runtime-core-3.1.17.jar:na]
	at com.speedment.runtime.core.internal.db.AbstractDbmsOperationHandler.execute(AbstractDbmsOperationHandler.java:166) ~[runtime-core-3.1.17.jar:na]
	at com.speedment.runtime.core.internal.db.AbstractDbmsOperationHandler.executeInsert(AbstractDbmsOperationHandler.java:142) ~[runtime-core-3.1.17.jar:na]
	at com.speedment.runtime.core.internal.component.sql.SqlPersistenceProviderImpl.persist(SqlPersistenceProviderImpl.java:171) ~[runtime-core-3.1.17.jar:na]
	at com.speedment.runtime.core.internal.component.sql.SqlPersistenceProviderImpl.lambda$persister$7(SqlPersistenceProviderImpl.java:154) ~[runtime-core-3.1.17.jar:na]
	at com.speedment.runtime.core.manager.Manager.persist(Manager.java:178) ~[runtime-core-3.1.17.jar:na]
	at {... removed...}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[na:1.8.0_201]
```

**Comment by dekmm** [comment]
I've tested this on a local Postgres 12 instance using Speedment 3.1.18. JSON data retrieval and persistence works just fine, so this was probably fixed at some point between 3.1.17 and 3.1.18.
