### ISSUE TITLE
Unable to generate a license file

### ISSUE THREAD

**Issue by jCube1980** [speedment/speedment#762]
I'm behind a corporate proxy and I have configured Maven to use the proxy in settings.xml

When I run 
`mvn speedment:tool` 
and enter the developer details, the following error is thrown. 

Basically, if I provide the SSL certificate of the license server in a keystore file, I believe I can resolve the issue. Does anyone know the URL of the licensing server? I would like to download the ssl certificate. 

INFO: Could not load @font-face font [jar:file:/C:/Users/userid/.m2/repository/com/speedment/enterprise/enterprise-tool/3.1.16/enterprise-tool-3.1.16.jar!/fonts/SourceCodePro-Regular.otf]
Aug 29, 2019 1:38:17 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 10.0.1 by JavaFX runtime of version 8.0.45
Aug 29, 2019 1:38:17 PM com.sun.javafx.css.StyleManager loadStylesheetUnPrivileged
INFO: Could not load @font-face font [jar:file:/C:/Users/userid/.m2/repository/com/speedment/enterprise/enterprise-tool/3.1.16/enterprise-tool-3.1.16.jar!/fonts/SourceCodePro-Regular.otf]
java.util.concurrent.CompletionException: java.lang.RuntimeException: Could not send POST-command.
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1584)
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1574)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.RuntimeException: Could not send POST-command.
        at com.speedment.common.rest.RestImpl.lambda$send$7(RestImpl.java:303)
        at com.speedment.common.rest.RestImpl$$Lambda$776/32225778.get(Unknown Source)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582)
        ... 5 more
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1937)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1478)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1050)

**Comment by minborg** [comment]
Thanks for your message. The license server is located at `service.speedment.com` and is indeed contacted over https as you mention. Let me know if this works for you!

**Comment by jCube1980** [comment]
@minborg, I downloaded and imported the certificate to a keystore file and passed it as a param while running maven on the command line like so, 

`mvn speedment:tool -Djavax.net.ssl.trustStore=/path/to/keystorefile`

However, I still have the issue. I'm on version 3.1.16. On version 3.1.17, it fails to even display the prompt for developer input and crashes before that. BTW, I'm now outside the corporate network (not behind a proxy now).

**Comment by minborg** [comment]
That does not sound good at all. Did you get a stack trace that you can share? I looks like you are running under Windows, is that right?

**Comment by minborg** [comment]
Send me an email to minborg at speedment dot com and I will send you a manually generated license so you can continue.

**Comment by jCube1980** [comment]
Thanks! and appreciate your help. I needed this to get a high profile team in my company interested, in speedment. I'll send you an email.
