### ISSUE TITLE
Jenkins tests fails at EncapsulationTest

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#815]
```
INFO] Running com.speedment.common.codegenxml.EncapsulationTest
[ERROR] Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.099 s <<< FAILURE! - in com.speedment.common.codegenxml.EncapsulationTest
[ERROR] deepReflection  Time elapsed: 0.07 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: The module com.speedment.common.codegen is not encapsulated for deep reflection
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:109)
	at com.speedment.common.codegenxml@3.2.0-SNAPSHOT/com.speedment.common.codegenxml.EncapsulationTest.deepReflection(EncapsulationTest.java:32)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

**Comment by minborg** [comment]
I have disabled the test for now. Revisit this when Jenkins has updated the Java 11 version.
```
package com.speedment.common.codegenxml;

@Disabled("This test does not work for Jenkins, See #815")
final class EncapsulationTest {
```
