### ISSUE TITLE
Speedment generator files missing

### ISSUE THREAD

**Issue by TheLegendaryJedi** [speedment/speedment#869]
Hi,

The generator on your website is only generating the pom file, nothing more.

Thanks

**Comment by julgus** [comment]
Starting from the release of Speedment 3.2.9 a few days back, this is actually the intended behavior. The main.java-file that was previously included in the download is now generated as an EntryPoint along with the database domain model. The generator will also create the project structure. The intention with this change is to provide a better EntryPoint as the previous main-file was very general and had no knowledge of e.g. the name of the user-specific ApplicationBuilder. 

I realize our quick-start guides are may be a bit misleading at this time. They will all be updated shortly to reflect these changes. 

Thank you for taking the time to reach out!

**Comment by TheLegendaryJedi** [comment]
Hi,
I used the spring boot initializer to scaffold the project structure and then added the pom file from your generator, the problem is when I run `mvn speedment: tool` and try to use the free licence it gives an error because it can't write the key to the speedment.json file because it does not exist. I tried to create it, but then it gives me compile error because it does not have the expected structure.

What cmd's should I use to automatically generate the folder structure?

Thanks

**Comment by dekmm** [comment]
Hi @TheLegendaryJedi, 

Do you mind sending me the error you get when you use the free licence?

Thanks

**Comment by TheLegendaryJedi** [comment]
Hi @dekmm ,

I got this one on the completion exception:
```
java.util.concurrent.CompletionException: RestException{protocol=HTTPS, method=POST, host='service.speedment.com', port=0, username='null', path='licenses/free'}
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: RestException{protocol=HTTPS, method=POST, host='service.speedment.com', port=0, username='null', path='licenses/free'}
	at com.speedment.common.rest.RestImpl.lambda$send$8(RestImpl.java:323)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	... 5 more
Caused by: java.net.UnknownHostException: service.speedment.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:606)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:681)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:167)
	at com.speedment.common.rest.RestImpl.lambda$send$8(RestImpl.java:310)
	... 6 more
```

On terminal, I got this infos:
```
[INFO] Running speedment:tool
[INFO] MavenProject: template.exe:test:1.0.0-SNAPSHOT @ C:\Users\03077412\eclipse-workspace\test\pom.xml
[INFO] The expected .json-file '...\eclipse-workspace\test\src\main\json\speedment.json' does not exist.
abr 16, 2020 2:27:49 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 10.0.1 by JavaFX runtime of version 8.0.251
abr 16, 2020 2:27:51 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 10.0.1 by JavaFX runtime of version 8.0.251
```

**Comment by dekmm** [comment]
@TheLegendaryJedi based on the stacktrace that you provided, it seems that you're experiencing a network issue. Can you confirm that this error occurs only when you use the Spring Boot initializer?

**Comment by TheLegendaryJedi** [comment]
@dekmm, same error only using the pom file. The error completion exception is "Error writing license"

Thanks

**Comment by TheLegendaryJedi** [comment]
@dekmm I tried to use curl using cmd line, with http and https and it works.

**Comment by Trinaware** [comment]
> @dekmm I tried to use curl using cmd line, with http and https and it works.

Can you kindly explain how? thanks
