### ISSUE TITLE
java.sql.SQLException: No database selected, with speedment PoolableConnection

### ISSUE THREAD

**Issue by kushkadu** [speedment/speedment#911]
I'm using "com.speedment.runtime.core.component.connectionpool.PoolableConnection" in my code.

where, successfully get "PoolableConnection" from "ConnectionPoolComponent" using getConnection(Dbms) method,
**Code:**
PoolableConnection connection = pool.getConnection(Dbms);

Statement stmt = connection.createStatement();
ResultSet rs = stmt.executeQuery(query);            <-- **Got error here as shown below**

**Console:**
2020-11-19T09:28:34.454Z DEBUG [http-nio-8080-exec-10] (#CONNECTION) - getConnection(jdbc:mysql://127.0.0.1:3306?useUnicode=true&characterEncoding=UTF-8&useServerPrepStmts=true&zeroDateTimeBehavior=CONVERT_TO_NULL&nullNamePatternMatchesAll=true&useLegacyDatetimeCode=true&connectionCollation=utf8_general_ci&serverTimezone=UTC, user, *****)
2020-11-19T09:28:34.454Z DEBUG [http-nio-8080-exec-10] (#CONNECTION) - Reuse Connection: com.speedment.runtime.core.internal.pool.PoolableConnectionImpl@3b57dba4

java.sql.SQLException: No database selected
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1200)

**How to resolve this issue?**

**Comment by minborg** [comment]
What is the value of Dbms when you call `pool.getConnection()`?

**Comment by kushkadu** [comment]
DbmsImpl {"enabled": true, "expanded": true, "id": "hospy", "ipAddress": "127.0.0.1", "name": "hospy", "nameProtected": true, "port": 3306, "schemas": "[1]", "typeName": "MySQL", "username": "user"}

**Comment by minborg** [comment]
@dekmm will have a look at it. The code you have provided looks good. 

This is not the official way of using Speedment (that is streams) but anyway, it should work.
